### ISSUE TITLE
Ctrl+V removes all formatting

### ISSUE THREAD

**Issue by emp** [jhollingworth/bootstrap-wysihtml5#7] opened 2012-03-20 17:07 UTC
Chrome vRetail

Created a Header 1, added a numbered list, added a simple list, added a Header 2 then created a new paragraph with "lorem ipsum dolor sit amet", copied that snipped and pasted it to fill the paragraph, all styling is gone on the entire textarea.

**Comment by buzzedword** [comment] 2012-03-20 19:26
:( boo. Confirmed this is an issue. Just tried using onPaste/onAfterPaste events with designmode activation-- usually works for me with contentEditable blobs, but not this time.

Looks like @jhollingworth has to suss this one out alone. Sorry bud.

**Comment by codef0rmer** [comment] 2012-03-21 11:24
I've found the code that causing this issue but not sure why we need the skipped code so decided to paste the changes here. 

You can see below is the fire() method which gets called every-time you type or press any key being in an editor. 
``` fire: function(eventName, payload) {
           this.events = this.events || {};
                   var handlers = this.events[eventName] || [],
             i        = 0;  
            for (; i<handlers.length; i++) {
              // I've put .call() in if-else condition for paste:composer to skip first 2 calls in order to suppress the bug
                  if (eventName === 'paste:composer' && (i === 0 || i === 1)) {
                  console.log(eventName + " " + handlers[i]);
              } else { 
                handlers[i].call(this, payload);
              }
            }
            return this;
    },

```

2 calls I skipped : (which are causing a problem)
this.observe("paste:composer");               // This clears the formatting of existing content in an editor.
this.parent.observe("paste:composer");    // This clears the formatting of the content being pasted.

Hope this will help. 
```

**Comment by mpelzsherman** [comment] 2012-03-26 19:59
Reproduced in Firefox 11.0. Fix on the horizon?

**Comment by buzzedword** [comment] 2012-03-26 21:16
Keep posted to the main [xing/wysihtml5](https://github.com/xing/wysihtml5) branch-- once it gets sussed out there, it should be merged down here. That's definitely an issue with their editor.

**Comment by codef0rmer** [comment] 2012-03-28 05:28
I checked xing/wysihtml5 editor which does not have that bug. Need to look into bootstrap-wysihtml5.js

**Comment by buzzedword** [comment] 2012-03-28 05:31
Funny you just commented on it, they added more documentation for the events they publish which clears up some of the issues here. Looking into the composer events to monitor copy/paste actions.

_edit_ or I'm an idiot and didn't see the needle in the haystack there-- composer docs have just been chilling in the middle. My bad. Looking into it either way.

**Comment by sblatnik8** [comment] 2012-05-01 14:03
Oh thank goodness!!! I do document development work and have been having this problem for quite some time now. It is absolutely maddening (not to mention a huge time waster), and I've been unable to find a solution online despite extensive efforts to do so. I'm not a coding person so I'm afraid I can't contribute to the solution, but I am so grateful that you are looking into it and only hope I can figure out how to apply the solution when you find it (the tech language is well over my head).

**Comment by vinaykumard** [comment] 2012-06-16 18:49
Thanks  @codef0rmer it's working just fine..

**Comment by jhollingworth** [comment] 2012-06-17 19:42
Should be fixed now :)

**Closed as completed by jhollingworth** 2012-06-17 19:42 UTC
Labels: bug

**Comment by sblatnik8** [comment] 2012-06-28 13:52
Hi--This is such wonderful news!  

But I don't know what it means in terms of actual application. Do I have to do anything on my end? Download an update or something or is it just going to miraculously be working in both new AND old documents.

Thanks for help!

Cheers,

Susan

Susan Blatnik
Cook International, LLC
Document Development Services
2041 Weber Avenue
Chesapeake, VA 23320
757-366-5901 (office phone & fax)
757-348-1193 (mobile)

-----Original Message-----

**Comment by vinaykumard** [comment] 2012-06-28 18:34
# Search for

fire: function(eventName, payload) {
    this.events = this.events || {};
    var handlers = this.events[eventName] || [],
        i        = 0;
    for (; i<handlers.length; i++) {
      handlers[i].call(this, payload);
    }
    return this;
  },

# IN wysihtml5-0.3.0.js

# and replace it with

fire: function(eventName, payload) {
 this.events = this.events || {};
var handlers = this.events[eventName] || [],
i = 0;

for (; i<handlers.length; i++) {
// I've put .call() in if-else condition for paste:composer to skip first 2 calls in order to suppress the bug
if (eventName === 'paste:composer' && (i === 0 || i === 1)) {
console.log(eventName + " " + handlers[i]);
} else { 
handlers[i].call(this, payload);
}
}
return this;
  },

**Comment by sblatnik8** [comment] 2012-06-28 18:59
Dear Lord! LOL. I will find a program-competent friend to help me. I can write a dissertation like no one's business, but this stuff stymies me. 

Thank you so very much for the info. I can't express how grateful I am. (No one believed this was a problem. Thought I was crazy or an idiot or perhaps both.) 

Thanks again.

Cheers,

Susan

Susan Blatnik
Cook International, LLC
Document Development Services
2041 Weber Avenue
Chesapeake, VA 23320
757-366-5901 (office phone & fax)
757-348-1193 (mobile)

-----Original Message-----
